# services:
#    valkey:
#     image: valkey/valkey
#     ports:
#       - "6380:6379"
#    qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"

services:
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  api:
    build:
      context: ./
    command: npm start           # runs your "start" script
    ports:
      - "3006:3006"
    environment:
      - VALKEY_URL=redis://valkey:6379
      - QDRANT_URL=http://qdrant:6333
      - COHERE_API_KEY=0z9HRcNQwl826pUfjxFqpioEoHsjH59jMxbmrC9z
    depends_on:
      - valkey
      - qdrant

  worker:
    build:
      context: ./
    command: npm run worker      # runs only the worker
    environment:
      - VALKEY_URL=redis://valkey:6379
      - QDRANT_URL=http://qdrant:6333
      - COHERE_API_KEY=0z9HRcNQwl826pUfjxFqpioEoHsjH59jMxbmrC9z
    depends_on:
      - valkey
      - qdrant
